# Generated by Django 4.2.30 on 2026-06-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('deal_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🍽', max_length=10)),
                ('is_drink', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🏙', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('deal_count', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('deal_type', models.CharField(choices=[('BOGO', 'Buy One Get One'), ('COMBO', 'Combo Deal'), ('PERCENT_OFF', '% Off')], max_length=20)),
                ('deal_description', models.CharField(max_length=300)),
                ('savings_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('savings_percent', models.IntegerField(blank=True, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('thumbnail_emoji', models.CharField(default='🍽', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.area')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='api.category')),
            ],
            options={
                'ordering': ['-savings_amount', '-is_live'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('query', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('result_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.city'),
        ),
        migrations.CreateModel(
            name='SavedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='api.offer')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('session_key', 'offer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('city', 'slug')},
        ),
    ]
