# Generated by Django 4.2.30 on 2026-06-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_offer_offer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_bank_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_pre_book',
            field=models.BooleanField(default=False),
        ),
    ]
